version: "3.9"
services:
  mysql:
    build: ./mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - "./mysql/init.sql:/docker-entrypoint-initdb.d/1.sql"
  tomcat:
    build: .
    ports:
      - "8080:8080"